services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loja_vinil
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: loja_user
      MYSQL_PASSWORD: loja_pass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./back-end
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./back-end/.env
    depends_on:
      database:
        condition: service_healthy
    #ports:
    #  - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./front-end
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./front-end/.env

    depends_on:
      - backend
    #ports:
    #  - "5173:3000"
    networks:
      - app-network

  nginx:
    build: ./Nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
