version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: loja_vinil
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./back-end
    container_name: backend
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: loja_vinil
      JWT_SECRET: segredo_bem_secreto
      JWT_EXPIRES_IN: 7d
      NODE_ENV: production
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./front-end
    container_name: frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: /api/
    depends_on:
      - backend
    ports:
      - "5173:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
